services:
  frametv:
    image: ghcr.io/mrtncode/frametv-art-gallery:latest
    container_name: frametv_artgallery
    restart: always
    volumes:
      - frametv_data:/data
    network_mode: host # Network mode is used to allow the container to auto discover the frame TV. You can also use the default bridge mode and add the TV's IP manually in the UI.
    # Use this if you want to use the default bridge network mode
   #ports:
    #  - "8000:8005"
    environment:
      - SECRET_KEY=supersecretkey
      - FRAME_TV_DATA=/data
      # This is the port that the web server will listen on when using the host network mode. You can change it to any available port on your host machine.
      - "PORT=8005"

volumes:
  frametv_data:
